app:
  security:
    jwt-secret: "change-this-to-a-very-long-random-secret-for-real-env"
    jwt-expiration-minutes: 120

server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  thymeleaf:
    cache: ${THYMELEAF_CACHE:false}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.devsecops: ${APP_LOG_LEVEL:DEBUG}
  file:
    name: ${LOG_FILE:/var/log/axy8s-backend/app.log}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId}] [%thread] %logger{36} - %msg%n"

ui:
  enabled: ${UI_ENABLED:true}

