apiVersion: v1
kind: Secret
metadata:
  name: axy8s-backend-secret
type: Opaque
stringData:
  # App use
  DB_URL: jdbc:postgresql://postgres-axy8s-service:5432/axy8sdb
  DB_USERNAME: axy8suser
  DB_PASSWORD: axy8spass
  LOG_LEVEL: INFO
  APP_LOG_LEVEL: DEBUG
  LOG_FILE: /var/log/axy8s-backend/app.log
  SERVER_PORT: "8080"

  # Postgres Pod use
  POSTGRES_DB: axy8sdb
  POSTGRES_USER: axy8suser
  POSTGRES_PASSWORD: axy8spass
